### ISSUE TITLE
Reward video freezing on iOS 10 and 11

### ISSUE THREAD

**Issue by DmitrySemenyk** [ChartBoost/ios-sdk-example#45]
When try to show Chartboost Reward Video video are freezing on iOS version 10 and 11
![IMG_0052 (2)](https://user-images.githubusercontent.com/5001808/218925794-cb5f2040-6089-4022-b1a9-301712794e3f.PNG)

We using IronSource mediator
СhartBoost SDK version - 9.1.0

**Comment by arnaumartifont** [comment]
should be solved now, not related to the SDK.
